### ISSUE TITLE
Error cupy.cuda.memory.OutOfMemoryError: out of memory to allocate

### ISSUE THREAD

**Issue by ssalvadeo** [motokimura/spacenet_building_detection#3]
When trying to execute 

`python train_model.py ../../data/dataSplit ../../data/processedBuildingLabels/3band ../../data/buildingMaskImages`

I receive the following error:

```
/opt/conda/envs/py3.6/lib/python3.6/site-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
GPU: 0
# Minibatch-size: 16
# Crop-size: 400
# epoch: 50

Exception in main training loop: out of memory to allocate 163840000 bytes (total 1673061376 bytes)
Traceback (most recent call last):
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/trainer.py", line 304, in run
    update()
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/optimizer.py", line 593, in update
    loss = lossfun(*args, **kwds)
  File "/workspace/src/models/unet.py", line 95, in __call__
    h = self.forward(x)
  File "/workspace/src/models/unet.py", line 61, in forward
    e2 = F.relu(self.bnc2(self.c2(e1)))
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/functions/activation/relu.py", line 141, in relu
    y, = ReLU().apply((x,))
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/function_node.py", line 364, in forward
    return self.forward_gpu(inputs)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/functions/activation/relu.py", line 39, in forward_gpu
    y = cuda.cupy.maximum(x[0], 0)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 804, in cupy.core.core.ufunc.__call__
  File "cupy/core/elementwise.pxi", line 381, in cupy.core.core._get_out_args
  File "cupy/core/core.pyx", line 95, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 439, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 916, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 937, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 749, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 731, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 664, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 394, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 395, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 67, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 214, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 737, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 664, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 394, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 395, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 67, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 214, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 743, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 664, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 394, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 395, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 67, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 214, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_model.py", line 152, in <module>
    train_model()
  File "train_model.py", line 148, in train_model
    trainer.run()
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/trainer.py", line 318, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/trainer.py", line 304, in run
    update()
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/optimizer.py", line 593, in update
    loss = lossfun(*args, **kwds)
  File "/workspace/src/models/unet.py", line 95, in __call__
    h = self.forward(x)
  File "/workspace/src/models/unet.py", line 61, in forward
    e2 = F.relu(self.bnc2(self.c2(e1)))
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/functions/activation/relu.py", line 141, in relu
    y, = ReLU().apply((x,))
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/function_node.py", line 364, in forward
    return self.forward_gpu(inputs)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/chainer/functions/activation/relu.py", line 39, in forward_gpu
    y = cuda.cupy.maximum(x[0], 0)
  File "/opt/conda/envs/py3.6/lib/python3.6/site-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 804, in cupy.core.core.ufunc.__call__
  File "cupy/core/elementwise.pxi", line 381, in cupy.core.core._get_out_args
  File "cupy/core/core.pyx", line 95, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 439, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 916, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 937, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 749, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 163840000 bytes (total 1673061376 bytes)
```

**Comment by motokimura** [comment]
According to the error message, memory size of your GPU device seems to be insufficient for the default batch size. Can you try with `--batchsize` option? 

```
$ python train_model.py ../../data/dataSplit ../../data/processedBuildingLabels/3band ../../data/buildingMaskImages --batchsize 8
```

Because the default batch size is set to 16, required memory size will decrease by half with the example above.

**Comment by ssalvadeo** [comment]
Continues the same erros, these are the data of my computer, what minimal memory should I have? or how could this problem be solved


```
 *-core
       descripción: Placa base
       producto: H310M-HDV
       fabricante: ASRock
       id físico: 0
       serie: M80-B5014702592
     *-memory
          descripción: Memoria de sistema
          id físico: 9
          ranura: Placa de sistema o placa base
          tamaño: 8GiB
        *-bank:0
             descripción: DIMM DDR4 Síncrono 2667 MHz (0,4 ns)
             producto: BLS8G4D26BFSBK.8FD
             fabricante: 859B
             id físico: 0
             serie: A91EB06E
             ranura: ChannelA-DIMM0
             tamaño: 8GiB
             anchura: 64 bits
             reloj: 2667MHz (0.4ns)
     *-cpu
          descripción: CPU
          producto: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
          fabricante: Intel Corp.
          id físico: 15
          información del bus: cpu@0
          versión: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
          serie: To Be Filled By O.E.M.
          ranura: CPUSocket
          tamaño: 1548MHz
          capacidad: 4005MHz
          anchura: 64 bits
          reloj: 100MHz
      *-display
                descripción: VGA compatible controller
                producto: GM107GL [Quadro K620]
                fabricante: NVIDIA Corporation
                id físico: 0
                información del bus: pci@0000:01:00.0
                versión: a2
                anchura: 64 bits
                reloj: 33MHz
                capacidades: pm msi pciexpress vga_controller bus_master cap_list rom
                configuración: driver=nvidia latency=0
                recursos: irq:126 memoria:a2000000-a2ffffff memoria:90000000-9fffffff memoria:a0000000-a1ffffff ioport:4000(size=128) memoria:c0000-dffff
           *-multimedia
                descripción: Audio device
                producto: NVIDIA Corporation
                fabricante: NVIDIA Corporation
                id físico: 0.1
                información del bus: pci@0000:01:00.1
                versión: a1
                anchura: 32 bits
                reloj: 33MHz
                capacidades: pm msi pciexpress bus_master cap_list
                configuración: driver=snd_hda_intel latency=0
                recursos: irq:17 memoria:a3080000-a3083fff
        *-disk
             descripción: ATA Disk
             producto: KINGSTON SA400S3
             id físico: 0.0.0
             información del bus: scsi@0:0.0.0
             nombre lógico: /dev/sda
             versión: B1D1
             serie: 50026B76823F300B
             tamaño: 223GiB (240GB)
             capacidades: partitioned partitioned:dos
             configuración: ansiversion=5 logicalsectorsize=512 sectorsize=512 signature=b061fbf9
```

**Comment by motokimura** [comment]
Ok, please try:

```
python train_model.py ../../data/dataSplit ../../data/processedBuildingLabels/3band ../../data/buildingMaskImages --batchsize 1
```
